#ifndef INCLUDE_H
#define INCLUDE_H

#include <QWidget>
#include <QMainWindow>
#include <QApplication>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QDir>
#include <QMessageBox>
#include <QListWidget>
#include <QListWidgetItem>
#include <QPushButton>
#include <QString>
#include <QLineEdit>
#include <QComboBox>
#include <QWidget>
#include <QLabel>
#include <QEvent>
#include <QLineEdit>
#include <QFile>
#include <QDebug>
#include <QStringList>
#include <QRadioButton>
#include <QGroupBox>
#include <QCheckBox>
#include <QGridLayout>
#include <QHeaderView>
#include <QMdiSubWindow>
#include <QMainWindow>
#include <QLabel>
#include <QLineEdit>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QPushButton>
#include <QListWidget>
#include <QListWidgetItem>
#include <QTextEdit>
#include <QMessageBox>
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QSqlError>
#include <QSqlRecord>
#include <QDebug>
#include <QGraphicsView>
#include <QToolBar>
#include <QMdiArea>
#include <QMenuBar>
#include <QMenu>
#include <QString>
#include <QMdiSubWindow>
#include <QTableWidget>
#include <QSizePolicy>
#endif // INCLUDE_H